language: java

jdk:
    - oraclejdk8

env:
    - TERM=dumb

script:
    - "./gradlew clean unstableTests -i"

after_success:
    - "./gradlew jacocoRootReport coveralls"

branches:
  only:
    - 1268-reliable-board-tests

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

addons:
  apt:
    packages:
      - oracle-java8-installer
